# Generated by Django 4.0.4 on 2022-05-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('sell_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.FloatField()),
                ('send_email', models.BooleanField()),
                ('send_telegram', models.BooleanField()),
                ('send_sms', models.BooleanField()),
                ('send_discord', models.BooleanField()),
                ('price_hist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_tracker.pricehistory')),
            ],
        ),
    ]
