# Generated by Django 4.0.4 on 2022-05-11 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('price_tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trackers',
            new_name='Tracker',
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
